language: java
sudo: false
install: true

notifications:
  slack:
    rooms:
      - 1705may15java:$SLACK_TOKEN
    on_success: never
    on_failure: always

addons:
  sonarqube:
    organization: $SONARQUBE_ORG
    token:
      secure: $SONARQUBE_TOKEN

jdk:
  - oraclejdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'